import {
  ArchetypeBenchmark,
  EvaluationContext,
  EvidenceLink,
  MitigationAction,
  ProjectProfile,
  ReadinessTarget,
  RiskIssue,
  ScoringModelVersion,
  ScenarioDefinition,
} from "./types";

const project: ProjectProfile = {
  id: "proj-atlas-green-steel",
  name: "Atlas Green Steel Corridor",
  sector: "Industrial infrastructure",
  stage: "Mandated lead arranger diligence",
  sponsor: "Pan-African Metals Consortium",
  geography: "Cameroon / CEMAC",
  debtAskUsdM: 420,
};

const evidence: EvidenceLink[] = [
  {
    id: "ev-feasibility",
    title: "Independent technical feasibility study",
    href: "/evidence/feasibility-study.pdf",
    excerpt: "Phase 1 capex, schedule float, and ramp-up assumptions validated by owner engineer.",
    strength: "strong",
    updatedAt: "2026-03-01",
  },
  {
    id: "ev-offtake",
    title: "Signed offtake term sheet",
    href: "/evidence/offtake-term-sheet.pdf",
    excerpt: "Tier-1 buyer covers 58% of phase 1 volumes with floor-price collar.",
    strength: "strong",
    updatedAt: "2026-02-21",
  },
  {
    id: "ev-model",
    title: "Base case financial model v17",
    href: "/evidence/financial-model.xlsx",
    excerpt: "LLCR and DSCR sensitivities refreshed with energy-price downside scenario.",
    strength: "moderate",
    updatedAt: "2026-03-05",
  },
  {
    id: "ev-esia",
    title: "ESIA and biodiversity management plan",
    href: "/evidence/esia.pdf",
    excerpt: "Resettlement and water-intensity mitigations remain conditional on agency sign-off.",
    strength: "moderate",
    updatedAt: "2026-02-18",
  },
  {
    id: "ev-permits",
    title: "Permitting tracker",
    href: "/evidence/permits-tracker.xlsx",
    excerpt: "Grid interconnection permit remains pending final ministry countersignature.",
    strength: "weak",
    updatedAt: "2026-03-07",
  },
  {
    id: "ev-epc",
    title: "EPC wrap and interface matrix",
    href: "/evidence/epc-wrap.pdf",
    excerpt: "Liquidated damages accepted, but commissioning interfaces are still fragmented.",
    strength: "moderate",
    updatedAt: "2026-03-03",
  },
];

const issues: RiskIssue[] = [
  {
    id: "risk-grid-permit",
    title: "Grid interconnection permit not yet countersigned",
    domain: "regulatory",
    severity: "critical",
    status: "open",
    counterparty: "Energy ministry",
    workstream: "Permitting",
    owner: "Amina Sissoko",
    description: "Financial close remains exposed until the final interconnection permit is countersigned and gazetted.",
    mitigation: "Escalate joint sponsor-ministry workstream, introduce condition precedent tracking, and secure stop-date extension.",
    evidenceIds: ["ev-permits"],
  },
  {
    id: "risk-dscr",
    title: "Downside DSCR drops below lender hurdle",
    domain: "financial",
    severity: "high",
    status: "mitigating",
    counterparty: "Model / lenders",
    workstream: "Financing",
    owner: "David Nnaji",
    description: "Under energy-price downside, minimum DSCR compresses below 1.20x.",
    mitigation: "Add reserve sculpting, revise dividend lock-up, and expand contracted energy hedge coverage.",
    evidenceIds: ["ev-model"],
  },
  {
    id: "risk-water",
    title: "Water stewardship commitments incomplete",
    domain: "esg",
    severity: "medium",
    status: "open",
    counterparty: "ESG regulator",
    workstream: "ESG",
    owner: "Clarisse Bekono",
    description: "Lender expectations require a more explicit drought-contingency protocol and disclosure pack.",
    mitigation: "Issue revised water balance, emergency drawdown protocol, and community monitoring dashboard.",
    evidenceIds: ["ev-esia"],
  },
  {
    id: "risk-interface",
    title: "Commissioning interface accountability split across EPC lots",
    domain: "execution",
    severity: "high",
    status: "mitigating",
    counterparty: "EPC consortium",
    workstream: "Delivery",
    owner: "Luc Mbarga",
    description: "Schedule certainty deteriorates if performance testing ownership remains fragmented.",
    mitigation: "Consolidate interface management office and impose unified completion incentives.",
    evidenceIds: ["ev-epc"],
  },
];

const mitigationRegister: MitigationAction[] = [
  {
    id: "mit-1",
    issueId: "risk-grid-permit",
    title: "Weekly permitting war-room with ministry legal desk",
    owner: "Amina Sissoko",
    dueDate: "2026-03-20",
    status: "open",
    workstream: "Permitting",
    evidenceIds: ["ev-permits"],
  },
  {
    id: "mit-2",
    issueId: "risk-dscr",
    title: "Refresh sculpted debt service reserve case",
    owner: "David Nnaji",
    dueDate: "2026-03-18",
    status: "mitigating",
    workstream: "Financing",
    evidenceIds: ["ev-model"],
  },
  {
    id: "mit-3",
    issueId: "risk-water",
    title: "Publish drought contingency operating protocol",
    owner: "Clarisse Bekono",
    dueDate: "2026-03-24",
    status: "open",
    workstream: "ESG",
    evidenceIds: ["ev-esia"],
  },
  {
    id: "mit-4",
    issueId: "risk-interface",
    title: "Approve integrated commissioning responsibility matrix",
    owner: "Luc Mbarga",
    dueDate: "2026-03-16",
    status: "mitigating",
    workstream: "Delivery",
    evidenceIds: ["ev-epc"],
  },
];

const readinessTargets: ReadinessTarget[] = [
  {
    id: "readiness-project",
    type: "project",
    label: "Project overall",
    relatedCriteriaIds: [
      "tech-feasibility",
      "comm-offtake",
      "fin-dscr",
      "reg-permits",
      "esg-water",
      "exec-epc",
    ],
  },
  {
    id: "readiness-permitting",
    type: "workstream",
    label: "Permitting workstream",
    domainWeights: { regulatory: 0.7, execution: 0.3 },
    relatedCriteriaIds: ["reg-permits", "exec-epc"],
  },
  {
    id: "readiness-sponsor",
    type: "counterparty",
    label: "Sponsor and delivery counterparties",
    domainWeights: { commercial: 0.2, execution: 0.5, financial: 0.3 },
    relatedCriteriaIds: ["comm-offtake", "exec-epc", "fin-dscr"],
  },
];

const scoringModel: ScoringModelVersion = {
  id: "atlas-model-v1",
  name: "Atlas greenfield infrastructure bankability model",
  version: "1.0.0",
  effectiveDate: "2026-03-12",
  domainWeights: {
    technical: 0.18,
    commercial: 0.16,
    financial: 0.22,
    regulatory: 0.16,
    esg: 0.12,
    execution: 0.16,
  },
  criteria: [
    {
      id: "tech-feasibility",
      domain: "technical",
      label: "Technical feasibility and operability",
      description: "Independent validation of design basis, ramp-up, and process stability.",
      weight: 1,
      score: 78,
      owner: "Owner engineer",
      threshold: 70,
      evidenceIds: ["ev-feasibility"],
    },
    {
      id: "comm-offtake",
      domain: "commercial",
      label: "Offtake depth and pricing resilience",
      description: "Credible revenue stack with buyer quality and price protection.",
      weight: 1,
      score: 82,
      owner: "Commercial team",
      threshold: 70,
      evidenceIds: ["ev-offtake"],
    },
    {
      id: "fin-dscr",
      domain: "financial",
      label: "Debt capacity and downside resilience",
      description: "Debt sizing, base-case coverage, covenant headroom, and reserve support.",
      weight: 1,
      score: 67,
      owner: "Financial adviser",
      threshold: 75,
      evidenceIds: ["ev-model"],
      notes: "Requires reserve sculpting and tighter dividend lock-up to reach target lender case.",
    },
    {
      id: "reg-permits",
      domain: "regulatory",
      label: "Permit completeness and change-in-law protection",
      description: "Status of permits, licenses, and government support package.",
      weight: 1,
      score: 52,
      owner: "Permitting counsel",
      threshold: 80,
      evidenceIds: ["ev-permits"],
    },
    {
      id: "esg-water",
      domain: "esg",
      label: "ESG actionability and stakeholder defensibility",
      description: "Water, biodiversity, resettlement, and disclosure readiness.",
      weight: 1,
      score: 64,
      owner: "ESG adviser",
      threshold: 70,
      evidenceIds: ["ev-esia"],
    },
    {
      id: "exec-epc",
      domain: "execution",
      label: "Delivery structure and completion certainty",
      description: "EPC wrap, interfaces, performance guarantees, and schedule control.",
      weight: 1,
      score: 61,
      owner: "Delivery office",
      threshold: 72,
      evidenceIds: ["ev-epc"],
    },
  ],
  redFlagRules: [
    {
      id: "rf-permit-critical",
      label: "Critical permit incompleteness",
      description: "Any critical open regulatory issue blocks investment-grade readiness.",
      domain: "regulatory",
      severity: "critical",
      predicate: (context) =>
        context.issues.some((issue) => issue.domain === "regulatory" && issue.severity === "critical" && issue.status !== "closed"),
      mitigationTemplate: "Treat as CP to debt close and maintain sponsor-led escalation until issuance.",
    },
    {
      id: "rf-financial-threshold",
      label: "Financial downside below hurdle",
      description: "Financial criterion score below model threshold indicates underwritten downside fragility.",
      domain: "financial",
      severity: "high",
      predicate: (context) =>
        context.scoringModel.criteria.some(
          (criterion) => criterion.domain === "financial" && criterion.score < criterion.threshold,
        ),
      mitigationTemplate: "Rebalance debt sculpting, reserve sizing, and contracted revenue before term sheet finalization.",
    },
  ],
};

const benchmark: ArchetypeBenchmark = {
  id: "arch-greenfield-export",
  label: "Emerging-market greenfield export project benchmark",
  sector: "Industrial infrastructure",
  expectedDomainScores: {
    technical: 80,
    commercial: 76,
    financial: 74,
    regulatory: 72,
    esg: 70,
    execution: 73,
  },
  notes: "Comparable projects typically secure lender comfort only after regulatory and execution scores clear the low-70s.",
};

export const scenarios: ScenarioDefinition[] = [
  {
    mode: "base",
    label: "Base case",
    description: "Current diligence snapshot with no counterfactual adjustments.",
    adjustments: [],
  },
  {
    mode: "downside",
    label: "Commodity and power downside",
    description: "Stresses permit delay, energy costs, and completion interfaces.",
    adjustments: [
      { criterionId: "fin-dscr", delta: -9, reason: "Energy-price downside compresses debt service headroom." },
      { criterionId: "reg-permits", delta: -6, reason: "Permit countersignature delay pushes long-stop date." },
      { criterionId: "exec-epc", delta: -5, reason: "Commissioning fragmentation increases schedule risk." },
    ],
  },
  {
    mode: "upside",
    label: "Mitigation delivery upside",
    description: "Assumes permit close-out, reserve sculpting, and interface cleanup are delivered.",
    adjustments: [
      { criterionId: "fin-dscr", delta: 10, reason: "Reserve sculpting restores minimum coverage above hurdle." },
      { criterionId: "reg-permits", delta: 18, reason: "Final permit countersigned and embedded in CP list." },
      { criterionId: "exec-epc", delta: 8, reason: "Unified commissioning office improves completion certainty." },
      { criterionId: "esg-water", delta: 6, reason: "Water stewardship protocol closes lender disclosure gap." },
    ],
  },
];

export function getAtlasBankabilityContext(): EvaluationContext {
  return {
    project,
    scoringModel,
    evidence,
    issues,
    mitigations: mitigationRegister,
    readinessTargets,
    benchmark,
  };
}
