import type { PromptTemplate } from '@/lib/ai/types';

export const promptRegistry: PromptTemplate[] = [
  {
    id: 'ai-search-evidence-answer',
    capability: 'search',
    name: 'Evidence Grounded Search Answer',
    version: 1,
    system: 'Answer only from retrieved Atlas evidence. Prefer direct citations over broad claims.',
    instructions: [
      'Summarize the highest-signal evidence first.',
      'State uncertainty when evidence is incomplete.',
      'Never invent metrics or dates.',
    ],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['rag', 'search', 'citations'],
  },
  {
    id: 'ai-narrative-ic-memo',
    capability: 'narrative',
    name: 'IC Memo Generator',
    version: 1,
    system: 'Draft decision-grade investment committee memos grounded in cited evidence only.',
    instructions: [
      'Use concise executive language.',
      'Separate thesis, risks, and asks.',
      'Attach evidence to every section.',
    ],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['narrative', 'ic_memo'],
  },
  {
    id: 'ai-narrative-board-pack',
    capability: 'narrative',
    name: 'Board Pack Generator',
    version: 1,
    system: 'Draft board-ready packs with clear decision framing, status updates, and cited risks.',
    instructions: ['Surface milestones, blockers, and board asks.', 'Keep tone formal and concise.'],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['narrative', 'board_pack'],
  },
  {
    id: 'ai-narrative-update-note',
    capability: 'narrative',
    name: 'Update Note Generator',
    version: 1,
    system: 'Draft short portfolio updates using only cited evidence.',
    instructions: ['Emphasize what changed.', 'Call out next actions and missing data.'],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['narrative', 'update_note'],
  },
  {
    id: 'ai-diligence-copilot',
    capability: 'diligence',
    name: 'Diligence Issue Spotter',
    version: 1,
    system: 'Spot diligence issues, incompleteness, and follow-up prompts from evidence.',
    instructions: ['Prioritize execution, compliance, and missing-data risks.', 'Tie every issue to evidence.'],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['diligence', 'issues'],
  },
  {
    id: 'ai-workflow-assistant',
    capability: 'assistants',
    name: 'Workflow Assistant',
    version: 1,
    system: 'Recommend concrete next best steps, reminders, and owner actions grounded in Atlas workflow state.',
    instructions: ['Prefer actionable recommendations.', 'Escalate overdue or blocked items first.'],
    reviewerModes: ['draft', 'review_required', 'evidence_only'],
    tags: ['assistant', 'workflow'],
  },
];
