import type { AssetDataset } from "@/types/assets";

const now = new Date("2026-03-12T08:00:00.000Z");

function hoursAgo(hours: number) {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

export const assetSeedData: AssetDataset = {
  assets: [
    {
      id: "asset-haul-01",
      name: "Komatsu 930E Haul Truck 01",
      site: "Mbalam North",
      category: "fleet",
      className: "Ultra-class haul truck",
      owner: "Mining Operations",
      status: "operational",
      utilizationTarget: 82,
      fuelTargetPerUnit: 0.58,
      energyTargetPerUnit: 0,
      throughputTarget: 720,
      inspectionDueAt: "2026-03-18T08:00:00.000Z",
      serviceIntervalHours: 720,
      runtimeHours: 684,
      commercialRatePerUnit: 12,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: "asset-crush-01",
      name: "Primary Crusher Line A",
      site: "Lobe Plant",
      category: "plant",
      className: "Jaw crusher",
      owner: "Processing Plant",
      status: "operational",
      utilizationTarget: 88,
      fuelTargetPerUnit: 0,
      energyTargetPerUnit: 5.4,
      throughputTarget: 610,
      inspectionDueAt: "2026-03-14T08:00:00.000Z",
      serviceIntervalHours: 480,
      runtimeHours: 466,
      commercialRatePerUnit: 9.5,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: "asset-gen-01",
      name: "Hybrid Power Plant Block 1",
      site: "Kribi Logistics Corridor",
      category: "energy",
      className: "Hybrid generation block",
      owner: "Energy Services",
      status: "operational",
      utilizationTarget: 90,
      fuelTargetPerUnit: 0.12,
      energyTargetPerUnit: 1,
      throughputTarget: 140,
      inspectionDueAt: "2026-03-16T08:00:00.000Z",
      serviceIntervalHours: 650,
      runtimeHours: 621,
      commercialRatePerUnit: 18,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
  ],
  connectors: [
    {
      id: "conn-haul-can",
      assetId: "asset-haul-01",
      type: "can_bus",
      label: "Truck CAN bus",
      status: "online",
      pollingIntervalMinutes: 5,
      lastSyncAt: now.toISOString(),
      mappedMetrics: ["utilization", "fuel_burn", "throughput", "vibration", "downtime_minutes"],
    },
    {
      id: "conn-crush-scada",
      assetId: "asset-crush-01",
      type: "scada",
      label: "Crusher SCADA",
      status: "online",
      pollingIntervalMinutes: 5,
      lastSyncAt: now.toISOString(),
      mappedMetrics: ["utilization", "energy_draw", "throughput", "temperature", "vibration", "inspection_score"],
    },
    {
      id: "conn-gen-erp",
      assetId: "asset-gen-01",
      type: "erp",
      label: "Power plant data broker",
      status: "degraded",
      pollingIntervalMinutes: 15,
      lastSyncAt: now.toISOString(),
      mappedMetrics: ["utilization", "fuel_burn", "energy_draw", "revenue", "inspection_score"],
    },
  ],
  telemetry: [
    { id: "t1", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "utilization", timestamp: hoursAgo(6), value: 78, unit: "%", quality: 0.98, tags: ["baseline"] },
    { id: "t2", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "utilization", timestamp: hoursAgo(1), value: 69, unit: "%", quality: 0.99, tags: ["live"] },
    { id: "t3", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "fuel_burn", timestamp: hoursAgo(6), value: 0.55, unit: "l/tonne", quality: 0.97, tags: ["baseline"] },
    { id: "t4", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "fuel_burn", timestamp: hoursAgo(1), value: 0.71, unit: "l/tonne", quality: 0.97, tags: ["live"] },
    { id: "t5", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "throughput", timestamp: hoursAgo(1), value: 640, unit: "tph", quality: 0.98, tags: ["live"] },
    { id: "t6", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "vibration", timestamp: hoursAgo(6), value: 4.9, unit: "mm/s", quality: 0.96, tags: ["baseline"] },
    { id: "t7", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "vibration", timestamp: hoursAgo(1), value: 7.2, unit: "mm/s", quality: 0.96, tags: ["live"] },
    { id: "t8", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "downtime_minutes", timestamp: hoursAgo(1), value: 44, unit: "minutes", quality: 0.95, tags: ["live"] },
    { id: "t9", assetId: "asset-haul-01", connectorId: "conn-haul-can", metric: "revenue", timestamp: hoursAgo(1), value: 7680, unit: "usd/hour", quality: 0.96, tags: ["derived"] },

    { id: "t10", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "utilization", timestamp: hoursAgo(6), value: 90, unit: "%", quality: 0.98, tags: ["baseline"] },
    { id: "t11", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "utilization", timestamp: hoursAgo(1), value: 92, unit: "%", quality: 0.98, tags: ["live"] },
    { id: "t12", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "energy_draw", timestamp: hoursAgo(6), value: 5.1, unit: "kwh/tonne", quality: 0.97, tags: ["baseline"] },
    { id: "t13", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "energy_draw", timestamp: hoursAgo(1), value: 6.3, unit: "kwh/tonne", quality: 0.97, tags: ["live"] },
    { id: "t14", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "throughput", timestamp: hoursAgo(1), value: 625, unit: "tph", quality: 0.99, tags: ["live"] },
    { id: "t15", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "temperature", timestamp: hoursAgo(1), value: 96, unit: "c", quality: 0.95, tags: ["live"] },
    { id: "t16", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "vibration", timestamp: hoursAgo(1), value: 8.9, unit: "mm/s", quality: 0.94, tags: ["live"] },
    { id: "t17", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "inspection_score", timestamp: hoursAgo(2), value: 82, unit: "score", quality: 0.93, tags: ["inspection"] },
    { id: "t18", assetId: "asset-crush-01", connectorId: "conn-crush-scada", metric: "revenue", timestamp: hoursAgo(1), value: 5937.5, unit: "usd/hour", quality: 0.96, tags: ["derived"] },

    { id: "t19", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "utilization", timestamp: hoursAgo(6), value: 93, unit: "%", quality: 0.9, tags: ["baseline"] },
    { id: "t20", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "utilization", timestamp: hoursAgo(1), value: 81, unit: "%", quality: 0.87, tags: ["live"] },
    { id: "t21", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "fuel_burn", timestamp: hoursAgo(6), value: 0.11, unit: "l/kwh", quality: 0.88, tags: ["baseline"] },
    { id: "t22", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "fuel_burn", timestamp: hoursAgo(1), value: 0.16, unit: "l/kwh", quality: 0.86, tags: ["live"] },
    { id: "t23", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "energy_draw", timestamp: hoursAgo(1), value: 1.18, unit: "kwh/kwh", quality: 0.85, tags: ["live"] },
    { id: "t24", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "inspection_score", timestamp: hoursAgo(3), value: 74, unit: "score", quality: 0.9, tags: ["inspection"] },
    { id: "t25", assetId: "asset-gen-01", connectorId: "conn-gen-erp", metric: "revenue", timestamp: hoursAgo(1), value: 2520, unit: "usd/hour", quality: 0.88, tags: ["live"] }
  ],
  anomalies: [],
  maintenance: [],
  alerts: [],
  compliance: [
    {
      assetId: "asset-haul-01",
      status: "ready",
      inspectionDueAt: "2026-03-18T08:00:00.000Z",
      lastInspectionScore: 91,
      requiredDocuments: [
        { name: "Operator checklist", present: true },
        { name: "Brake certification", present: true },
        { name: "Insurance rider", present: true }
      ],
      openFindings: [],
    },
    {
      assetId: "asset-crush-01",
      status: "watch",
      inspectionDueAt: "2026-03-14T08:00:00.000Z",
      lastInspectionScore: 82,
      requiredDocuments: [
        { name: "Lifting inspection", present: true },
        { name: "Wear liner report", present: false },
        { name: "Guarding validation", present: true }
      ],
      openFindings: ["Wear liner replacement evidence missing"],
    },
    {
      assetId: "asset-gen-01",
      status: "non_compliant",
      inspectionDueAt: "2026-03-16T08:00:00.000Z",
      lastInspectionScore: 74,
      requiredDocuments: [
        { name: "Emissions log", present: false },
        { name: "Grid synchronization certificate", present: true },
        { name: "Fuel handling SOP signoff", present: false }
      ],
      openFindings: ["Emissions evidence overdue", "Fuel handling SOP signoff expired"],
    },
  ],
};
